### ISSUE TITLE
Quarkus in dev mode makes Unleash client crash after reload

### ISSUE THREAD

**Issue by mehmandarov** [quarkiverse/quarkus-unleash#125]
Running Quarkus in dev mode makes Unleash client crash with following error after reload : 

`2023-01-23 18:01:25,510 ERROR [io.get.uti.UnleashScheduledExecutorImpl] (Quarkus Main Thread) Unleash background task crashed [Error Occurred After Shutdown]: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@3c04bd52[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@3feb13e1[Wrapped task = io.getunleash.repository.FeatureRepository$$Lambda$1115/0x00000008011f1fd8@853b940]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7315d9c7[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 4]`

How to reproduce:
1. Create a Quarkus app and add Unleash using quarkus-unleash as described in Readme.
2. Get the app up and running, make sure that the Unleash toggles are read and working. Also, make sure that there are no errors in the logs.
3. Make changes in the app code, hit save.
4. Access the same endpoint using the Unleash toggles. Now you should see the similar stack trace in the logs.

**Comment by andrejpetras** [comment]
@mehmandarov thank you for the issue and the detailed description.
I fixed this issue in #133.

**Comment by andrejpetras** [comment]
Fix in v0.6.0 release
