### ISSUE TITLE
Disable the extension from the runtime configuration

### ISSUE THREAD

**Issue by gwenneg** [quarkiverse/quarkus-unleash#219]
Hey everyone! Thanks for creating this extension, it's great!

However, I'd like the ability to disable it from the runtime configuration and I didn't find a way to do that. It could be done with a simple `quarkus.unleash.enabled=true|false` config key.

Does that sound like a reasonable enhancement request? If so, I _might_ try to implement that myself, but I don't have a lot of time available so if anyone has free cycles before I do, please feel free to do it 😄

**Comment by gwenneg** [comment]
I took a quick look. This isn't as easy as I hoped, but still doable. I'll submit a PR next week.

**Comment by gsmet** [comment]
Ideally, if it's a runtime property to activate or not the extension, I would call it `active` to be consistent with what we do in core Quarkus.

**Comment by gwenneg** [comment]
Is `active` that common in Quarkus core? I see a lot of `enabled` config keys but not so many `active` ones. Or maybe that's a change in progress, from `enabled` to `active`?

**Comment by gsmet** [comment]
Let's say that we have both, `enabled` is used for build time and `active` for runtime.

It depends a bit of the meaning of what you're doing.

**Comment by gwenneg** [comment]
`quarkus-cache` should be updated then as it relies on `enabled` to enable/disable the extension at runtime.

**Comment by gsmet** [comment]
Well, I wouldn't break existing extensions just for the sake of it.
