### ISSUE TITLE
README.MD Add Configuration Docs

### ISSUE THREAD

**Issue by melloware** [quarkiverse/quarkus-unleash#95]
Great job on this extension. However I had to look at your source code for information on the Configuration options it would be nice if these were right inside the README.MD.    I can submit a PR if interested?

**Comment by andrejpetras** [comment]
@melloware thank you for the ticket. Yes, yes ... please submit a PR

**Comment by melloware** [comment]
On it. Will submit tomorrow.

**Comment by andrejpetras** [comment]
@melloware Excellent! Thank you

**Comment by melloware** [comment]
@all-contributors please add @melloware for doc
